export const GET_CATEGORY_BY_TITLE = "GET_CATEGORY_BY_TITLE"
export const GET_CATEGORY_NAMES = "GET_CATEGORY_NAMES"
export const LOAD_CATEGORY = "LOAD_CATEGORY"
export const CHANGE_CURRENCY_INDEX = "CHANGE_CURRENCY_INDEX"
export const GET_CURRENCIES = "GET_CURRENCIES"
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"
export const ADD_TO_MY_BAG = "ADD_TO_MY_BAG"
export const VIEW_MY_BAG = "VIEW_MY_BAG"

